### ISSUE TITLE
Installing ndl2 in Sharc

### ISSUE THREAD

**Issue by trallard** [ooominds/RSE-ticketing#1]
General issues regarding the installation of ndl2 in sharc.

## Detailed Description

When trying to install the package in a local folder in sharc the following message arises:
> package ‘ndl2’ is not available (for R version 3.4.0)

When the previous version is installed (ndl) and trying to load in R then the following error arises:
>Loading required package: ndl
Error: package or namespace load failed for ‘ndl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ld1ae/R/intel_R/sequential-3.4.0/ndl/libs/ndl.so':
  libRlapack.so: cannot open shared object file: No such file or directory 

## Context

Requested by the ooominders for data analysis

## Possible Implementation

After resolved, the steps should be documented in the group wiki for future reference

**Comment by trallard** [comment]
Tagging @Adnane017  as this was his original request

**Comment by mikecroucher** [comment]
I've now completed this and the writeup is currently in the ooominders HPC advice repo.

https://github.com/ooominds/HPC_advice/blob/master/README.md

Is this location suitable for the ndl2 documentation or should we move to the wiki?

**Comment by trallard** [comment]
I think it could live there for now. I can always point to this from our main wiki.

@Adnane017  could you confirm if Mike's solution works for you?

**Comment by Adnane017** [comment]
Yes, it works! Thanks!
