### ISSUE TITLE
Team members access to /shared/ooominds1/corpora on ShARC

### ISSUE THREAD

**Issue by macbormac** [ooominds/RSE-ticketing#4]
Team members need read access to /shared/ooominds1/corpora on ShARC

## Detailed Description
We (ldp17mjb, ldp17dh, ld1sm) can access only our user folders but not corpora

**Comment by trallard** [comment]
Done 🙂 you should have access to corpora now (the three of you, can you please let me know if this does not look right please?)

**Comment by striatum** [comment]
Perhaps if we would have some documentation how-to do this I could also add/remove access to specific (sub)directories. My guesstimate was that it's not Linux/Unix having weird user:group -> none:root, so I did not want to mess things up. Again, as I said, happy to do it in future, once I have clear idea how.

**Comment by trallard** [comment]
I can put together something if you're keen to take up on this @striatum. The way to do this is using a web interface. Alternatively, Will is already familiar with this and could take over.

**Comment by striatum** [comment]
I'm not really keen, but it might make sense in case Will is away or something. Don't you think? In sum, I can act in case of emergency, otherwise not.

**Comment by willfurnass** [comment]
@striatum Are you happy with the current process for enabling read-only access to `corpora` for certain users by
1. Browsing to https://www.sheffield.ac.uk/storage/
2. Clicking *Manage access rights*
3. Clicking *fstore_ooominds1_corpora-read*
4. Adding users who need access?

**Comment by striatum** [comment]
This is very straightforward! Many thanks!
