### ISSUE TITLE
Grant me the ability to close issues and assign people and labels to issues

### ISSUE THREAD

**Issue by willfurnass** [ooominds/RSE-ticketing#8]
@striatum Are you able to see what my current permissions are and how they differ from @trallard's, if she's still a member of this organisation?

**Comment by striatum** [comment]
This was created by @trallard. I do not see how can we add you and remove her? Any suggestion?

**Comment by willfurnass** [comment]
@mikecroucher Can you help with this?

**Comment by willfurnass** [comment]
Or @trallard, can you help?

**Comment by trallard** [comment]
Sorry, been on leave @willfurnass  will give you admin rights to the repo.  I will also do the same for Petar and Anna

**Comment by willfurnass** [comment]
Thanks @trallard !
