### ISSUE TITLE
ShARC: no access to project "rse" for user "ldp17mjb"

### ISSUE THREAD

**Issue by macbormac** [ooominds/RSE-ticketing#9]
## Description

When I submit a batch file or start an interactive session on sharc, and request the access to the rse queue(-P rse), I get the following message:
job rejected: no access to project "rse" for user "ldp17mjb"

## Expected Behavior

I should be able to access the queue
## Possible Fix

Access needs to be granted?
## Steps to Reproduce

in the terminal: 

[ldp17mjb@sharc-login2 ~]$ qrshx -P rse
job rejected: no access to project "rse" for user "ldp17mjb"

## Your Environment

* Environment name and version (e.g. Python 3.5, R 4.3):
* Operating System and version:
- [x] Tick of you are using ShARC
* Any additional libraries or dependencies you are using (e.g. Numpy, Pandas, tidyverse)
* Link to your project:

**Comment by willfurnass** [comment]
@maciejjborowski You should have access in the next 20 mins or so.  

Details of the nodes in the `rse` queue inc. info on how to use them can be found here:

http://docs.hpc.shef.ac.uk/en/latest/sharc/groupnodes/index.html

**Comment by macbormac** [comment]
Awesome, thanks @willfurnass!
